<a href="https://colab.research.google.com/github/klu2300030639/Arayan_May_AIML_TASK1/blob/main/Data_Preprocessing_Only_TEST3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

df = pd.read_csv("titanic.csv")

print("Dataset Shape:", df.shape)

print("\nMissing Values Before Cleaning")
print(df.isnull().sum())

df.drop_duplicates(inplace=True)

df["Age"].fillna(df["Age"].median(), inplace=True)
df["Embarked"].fillna(df["Embarked"].mode()[0], inplace=True)

df.drop("Cabin", axis=1, inplace=True)

df.drop(
    ["PassengerId", "Name", "Ticket"],
    axis=1,
    inplace=True
)

df = pd.get_dummies(
    df,
    columns=["Sex", "Embarked"],
    drop_first=True
)

X = df.drop("Survived", axis=1)
y = df["Survived"]

scaler = StandardScaler()

X = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

models = {
    "Logistic Regression":
        LogisticRegression(max_iter=1000),

    "KNN":
        KNeighborsClassifier(n_neighbors=5),

    "Random Forest":
        RandomForestClassifier(
            n_estimators=100,
            random_state=42
        )
}

result = []

for name, model in models.items():

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)

    pre = precision_score(y_test, y_pred)

    rec = recall_score(y_test, y_pred)

    f1 = f1_score(y_test, y_pred)

    cm = confusion_matrix(y_test, y_pred)

    print("\n")
    print("=" * 50)
    print(name)
    print("=" * 50)

    print("Accuracy :", round(acc, 4))
    print("Precision:", round(pre, 4))
    print("Recall   :", round(rec, 4))
    print("F1 Score :", round(f1, 4))

    print("\nConfusion Matrix")
    print(cm)

    result.append(
        [name, acc, pre, rec, f1]
    )

comparison = pd.DataFrame(
    result,
    columns=[
        "Algorithm",
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score"
    ]
)

print("\n")
print("=" * 50)
print("MODEL COMPARISON")
print("=" * 50)

print(
    comparison.sort_values(
        by="Accuracy",
        ascending=False
    )
)

Dataset Shape: (891, 12)

Missing Values Before Cleaning
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64


Logistic Regression
Accuracy : 0.8101
Precision: 0.7857
Recall   : 0.7432
F1 Score : 0.7639

Confusion Matrix
[[90 15]
 [19 55]]


KNN
Accuracy : 0.8045
Precision: 0.7826
Recall   : 0.7297
F1 Score : 0.7552

Confusion Matrix
[[90 15]
 [20 54]]


/tmp/ipykernel_11335/1027044241.py:25: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].median(), inplace=True)
/tmp/ipykernel_11335/1027044241.py:26: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)'



Random Forest
Accuracy : 0.8156
Precision: 0.7887
Recall   : 0.7568
F1 Score : 0.7724

Confusion Matrix
[[90 15]
 [18 56]]


MODEL COMPARISON
             Algorithm  Accuracy  Precision    Recall  F1 Score
2        Random Forest  0.815642   0.788732  0.756757  0.772414
0  Logistic Regression  0.810056   0.785714  0.743243  0.763889
1                  KNN  0.804469   0.782609  0.729730  0.755245
